//
//  MainPresenter.swift
//  MiloTestTask
//
//  Created by Oleksandr Nechet on 02.02.17.
//  Copyright (c) 2017 Oleksandr Nechet. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol MainPresenterInput
{
    func presentSomething(response: Main.Something.Response)
}

protocol MainPresenterOutput: class
{
    func displaySomething(viewModel: Main.Something.ViewModel)
}

class MainPresenter: MainPresenterInput
{
    weak var output: MainPresenterOutput!
    
    // MARK: - Presentation logic
    
    func presentSomething(response: Main.Something.Response)
    {
        let formattedResultMessage = "\(Constants.MainModule.resultMessage) \(response.result)"
        let viewModel = Main.Something.ViewModel(title: Constants.MainModule.resultTitle,
                                                 message: formattedResultMessage)
        DispatchQueue.main.async {
            self.output.displaySomething(viewModel: viewModel)
        }
    }
}
