//
//  MainModels.swift
//  MiloTestTask
//
//  Created by Oleksandr Nechet on 02.02.17.
//  Copyright (c) 2017 Oleksandr Nechet. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct Main
{
  struct Something
  {
    struct Request
    {
    }
    struct Response
    {
        let result: Int
    }
    struct ViewModel
    {
        let title: String
        let message: String
    }
  }
}
